version: "3.8"
services:
  mongo:
    image: mongo:4.0.26
    container_name: mongo
    volumes:
      - mongo-data:/data/db
      - mongo-config-data:/data/configdb
    ports:
      - 27017:27017

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  mysql:
    #image: mysql:
    image: mysql:5.7.37
    container_name: mysql
    #environment:
    #  - MYSQL_ROOT_PASSWORD=password
    env_file:
      - mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  postgres:
    image: postgres
    container_name: postgres
    #environment:
    #  - POSTGRES_PASSWORD=password
    env_file:
      - postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    #environment:
    #  - PGADMIN_DEFAULT_EMAIL=admin@example.com
    #  - PGADMIN_DEFAULT_PASSWORD=password
    #  - PGADMIN_LISTEN_PORT=5050
    env_file:
      - pgadmin.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-config-data:/root/.pgadmin
    ports:
      - 5050:5050


  jenkins:
#    build:
#      context: .
#      dockerfile: Dockerfile-jenkins
#      args:
#        - JENKINS_IMAGE=jenkins/jenkins:jdk11
#    image: ankurpathak/jenkins:jdk11
    image: jenkins/jenkins:jdk11
    user: root
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/ssguser/.sdkman:/usr/local/sdkman

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
      args:
        - TOMCAT_IMAGE=tomcat
    image: ankurpathak/tomcat
    container_name: tomcat
    ports:
      - 8081:8080

  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    env_file:
      - rabbit.env
    ports:
      - 15672:15672

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    env_file:
      - zookeeper.env
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    env_file:
      - kafka.env
    ports:
      - 9092:9092
      - 29092:29092

  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight-data:/db

  oracle:
    image: store/oracle/database-enterprise:12.2.0.1
    container_name: oracle
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/ORCL


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2-amd64
    container_name: elasticsearch
    env_file:
      - elasticsearch.env
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    env_file:
      - kibana.env
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  payara:
    image: payara/server-full
    container_name: payara
    ports:
      - "8080:8080"
      - "8181:8181" # HTTPS listener
      - "4848:4848" # HTTPS admin listener
      - "9009:9009" # Debug port
#    environment:
#    JVM_ARGS: ""
#     - "AS_ADMIN_MASTERPASSWORD=admin" #default password is `admin`
    volumes:
      - ./deployments:/opt/payara/deployments


  wildfly:
    image: jboss/wildfly
    container_name: wildfly
    ports:
      - "8080:8080"
      - "9990:9990" # admin listener
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
  #    environment:
  #./add-user.sh admin admin --silent
    volumes:
      - ./deployments:/opt/jboss/wildfly/standalone/deployments/

  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data
# temporary password in /nexus-data/admin.password


  #docker run -d -p 8081:8081 --name nexus sonatype/nexus3


  vault:
    image: vault
    container_name: vault
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK

  keyclock:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    ports:
      - 8080:8080



volumes:
  mongo-data:
    name: mongo-data
  mongo-config-data:
    name: mongo-data-configdb
  redis-data:
    name: redis-data
  mysql-data:
    name: mysql-data
  postgres-data:
    name: postgres-data
  pgadmin-data:
    name: pgadmin-data
  pgadmin-config-data:
    name: pgadmin-config-data
  jenkins-data:
    name: jenkins-data
  redisinsight-data:
    name: redisinsight-data
  elasticsearch-data:
    name: elasticsearch-data
  nexus-data:
    name: nexus-data
  oracle-data:
    name: oracle-data
    
    




#docker

#groupadd -g 999 docker
#usermod -aG docker jenkins

#https://github.com/Bash-it/bash-it/blob/master/completion/available/sdkman.completion.bash 